# This file is for defining fatal errors on which we are going to end the stories


USER_ID_NOT_PROVIDED = "Oops! It seems that I'm unable to identify your **User ID**."
COMPANY_ID_NOT_PROVIDED = "Oops! It seems that I'm unable to identify your **Company ID**."
LOCATION_ID_NOT_PROVIDED = "Oops! It seems that I'm unable to identify your **Location ID**."
CCID_NOT_PROVIDED = "Oops! It seems that I'm unable to identify your **Costing Company ID**."
COST_USER_NOT_PROVIDED = "Oops! It seems that I'm unable to identify your **Costing username**."
API_HOST_NOT_PROVIDED = "Oops! It seems that I'm unable to find the **API server**."
FG_CODE_NOT_PROVIDED = "Oops! It seems that I'm unable to extract the **FG code**.  \nPlease rephrase your sentence."
ACTIVITY_NAME_NOT_PROVIDED = "Oops! It seems that I'm unable to extract the **activity name**.  \nPlease rephrase " \
                             "your sentence."
API_RESULT_NOT_FINAL = "Oops! It seems that I didn't get a valid final result from the API server."
ORDER_OR_TNA_ID_NOT_PROVIDED = "Oops! It seems that I'm unable to identify the **Order ID** or" \
                        " **TNA Activity ID** of this option."
RAW_VENDOR_NAME_NOT_PROVIDED = "Oops! It seems that I'm unable to extract the **Supplier Name**."
VENDOR_NAME_CODE_NOT_PROVIDED = "Oops! It seems that I'm unable to extract a valid **Supplier Name**."
PO_TYPE_CODE_NOT_PROVIDED = "Oops! It seems that I'm unable to extract a valid **P.O. Type**."
PO_VENDOR_ATTRIBUTE_TO_CHANGE_NOT_PROVIDED = "Oops! It seems that I did not understand what you want to change."
PO_DETAIL_TYPE_CODE_NOT_PROVIDED = "Oops! It seems that I'm unable to extract the **P.O. detail type.**"
PO_DETAIL_TYPE_RAW_NUMBER_NOT_PROVIDED = "Oops! It seems that I'm unable to extract the number that you entered."
PO_DETAIL_TYPE_NUMBER_CODE_NOT_PROVIDED = "Oops! It seems that I'm unable to extract the number that you selected."
PO_NUMBER_NOT_FOUND_RE_ENTER = "I couldn't find anything with that number. Please check the number and enter again."
PO_API_ERROR = "Oops! It seems that the PO API is facing some problem. I'm quiting the PO making process."
PO_ITEM_OR_ACTIVITY_TYPE_CODE_NOT_PROVIDED = "Oops! It seems that I couldn't extract the **Item Type** or **Activity**"
PO_ACTIVITY_CODE_NOT_PROVIDED = "Oops! It seems that I couldn't extract the **Activity**"
PO_VENDOR_BILL_ADDRESS_CODE_NOT_PROVIDED = "Oops! It seems that I couldn't extract the **Bill Address**"
PO_VENDOR_SHIP_ADDRESS_CODE_NOT_PROVIDED = "Oops! It seems that I couldn't extract the **Ship Address**"
PO_VENDOR_PAY_TERMS_CODE_NOT_PROVIDED = "Oops! It seems that I couldn't extract the **Pay Terms**"
PO_VENDOR_DISPATCH_MODE_CODE_NOT_PROVIDED = "Oops! It seems that I couldn't extract the **Dispatch Mode**"
PO_VENDOR_CURRENCY_CODE_NOT_PROVIDED = "Oops! It seems that I couldn't extract the **Currency**"
PO_REMARKS_NOT_PROVIDED = "Oops! It seems that I didn't get your **Remarks**"
PO_CONVERSION_RATE_NOT_PROVIDED = "Oops! It seems that I couldn't extract the **Conversion Rate**."
PO_SELECTED_ITEMS_NOT_PROVIDED = "Oops! It seems that I didn't received any data from the pop-up."
PO_API_NO_RECORD_FOUND = "Oops! It seems that I couldn't find anything with that name/number."
CLIENT_CODE_NOT_PROVIDED = "Oops! It seems that I couldn't extract the **Client Code**."
PRINT_PDF_API_ERROR = "Oops! It seems that we are having some difficulty in generating the PDF Link."
SAVE_PO_API_ERROR = "Oops! It seems that we are having some difficulty in saving the P.O."
PO_MAKING_NOT_ALLOWED_ERROR = "Oops! It seems that you do not have permission to make PO"
DEFAULT_VENDOR_VALUES_NOT_FOUND = "Oops! It seems that I couldn't find default values of this vendor."
VENDOR_VALUES_TO_CHANGE_NOT_FOUND = "Oops! It seems that I couldn't find the values of " \
                                    "this vendor that you are allowed to change."
PO_ACTIVITY_LIST_NOT_FOUND = "Oops! It seems that I couldn't find the list of activities for you."
PO_ITEM_TYPE_LIST_NOT_FOUND = "Oops! It seems that I couldn't find the list of items for you."
PO_CURRENCY_LIST_NOT_FOUND = "Oops! It seems that I couldn't find the list of currency for you."
PO_DETAIL_TYPE_LIST_NOT_FOUND = "Oops! It seems that I couldn't find the list of PO detail type for you."
PO_GET_ITEM_DETAILS_API_ERROR = "Oops! It seems that we are having some difficulty in fetching the item details."
PO_GET_DETAIL_TYPE_NUMBER_LIST_API_ERROR = "Oops! It seems that we are having some" \
                                           " difficulty in searching what you entered."
PO_GET_VENDOR_LIST_API_ERROR = "Oops! It seems that we are having some difficulty in " \
                               "fetching the **Suppliers** of this name."
PO_LIST_TOP_THREE_API_ERROR = "Oops! It seems that we are having some difficulty in fetching the top results for this."
PO_SELECTED_ITEMS_NOT_SET = "Oops! It seems that I couldn't extract the selected items."


